### Numpy Basics

In [55]:
import numpy as np

In [56]:
my_list = [3, 4, 7, -2, 11]
my_list

[3, 4, 7, -2, 11]

In [57]:
my_list * 1.5

TypeError: can't multiply sequence by non-int of type 'float'

In [58]:
my_array = np.array(my_list)
my_array

array([ 3,  4,  7, -2, 11])

In [59]:
my_array * 1.5

array([ 4.5,  6. , 10.5, -3. , 16.5])

In [60]:
np.ones(5)    

array([1., 1., 1., 1., 1.])

In [61]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
# Run this code a few times to verify that you get -3, but never a +7
np.random.randint?
rnd_int = np.random.randint(low=-3, high=7, size=(4, 5))
print(rnd_int)

[[ 5  4  6  4 -3]
 [ 3 -3  3  2  0]
 [-2  2  4 -2 -1]
 [ 0 -3  4  0 -3]]


Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

#### Getting Lists of linearly seperated Values

In [42]:
np.arange(start=0, stop=4, step=1)

array([0, 1, 2, 3])

In [43]:
np.arange(start=2, stop=6, step=1)

array([2, 3, 4, 5])

In [45]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### Constants

In [46]:
np.pi

3.141592653589793

In [49]:
np.e

2.718281828459045

#### Random Arrays

In [24]:
b = np.random.random(10)
b

array([0.1416616 , 0.65804421, 0.21859171, 0.57403209, 0.4567118 ,
       0.92863735, 0.7820765 , 0.98031375, 0.88281544, 0.00530337])

In [25]:
a = np.linspace(0,4,10)
a * b

array([0.        , 0.29246409, 0.19430374, 0.76537612, 0.81193208,
       2.06363855, 2.08553733, 3.04986499, 3.13889933, 0.02121348])

In [50]:
a.dot(b)

12.423229724050302

#### Manipulation of arrays

In [53]:
ae = np.exp(b)
ae

array([1.15218668, 1.93101199, 1.24432312, 1.77541126, 1.57887378,
       2.53105787, 2.1860068 , 2.66529234, 2.41769701, 1.00531746])

In [54]:
np.log(ae)

array([0.1416616 , 0.65804421, 0.21859171, 0.57403209, 0.4567118 ,
       0.92863735, 0.7820765 , 0.98031375, 0.88281544, 0.00530337])


<table class="my">
  <tr>
    <th>Operation</th>
    <th>Description</th>
  </tr>
  <tr >
      <td><code>np.sum</code></td>
    <td>Sum of entries</td>
  </tr>
  <tr >
    <td><code>np.prod</code></td>
    <td>Product (multiplication) of all entries</td>
  </tr>
  <tr >
    <td><code>np.mean</code></td>
    <td>Arithmetic average</td>
  </tr>
  <tr >
    <td><code>np.std</code></td>
    <td>Standard deviation</td>
  </tr>  
  <tr >
    <td><code>np.var</code></td>
    <td>Variance</td>
  </tr>  
  <tr >
    <td><code>np.min</code></td>
    <td>Minimum value</td>
  </tr>  
  <tr >
    <td><code>np.max</code></td>
    <td>Maximum value</td>
  </tr>  
  <tr >
    <td><code>np.argmin</code></td>
    <td>Index of the minimum</td>
  </tr>  
  <tr >
    <td><code>np.argmax</code></td>
    <td>Index of the maximum</td>
  </tr>  
  <tr >
    <td><code>np.median</code></td>
    <td>Median value</td>
  </tr>      
</table>

In [31]:

import numpy as np
A = np.array([[8, 7], [6, 5], [4, 3], [2, 1]])
B = np.array([[1, 2, 3], [4, 5, 6]])
X = A @ B
print('Compact matrix multiplication: A@B = \n{}'.format(X))

Compact matrix multiplication: A@B = 
[[36 51 66]
 [26 37 48]
 [16 23 30]
 [ 6  9 12]]


Other linear algebra commands of interest in the ``linalg`` section of NumPy are:
* ``np.linalg.eig`` for eigenvalues and eigenvectors
* ``np.linalg.eigvals`` for the eigenvalues only
* ``np.linalg.svd``for the singular value decomposition (related to PCA)
* ``np.linalg.solve``for solving linear matrix equations
* ``np.linalg.solve``for solving linear matrix equations
